#!/usr/bin/expect

set timeout -1

# clone the Wind River Linux git repository
spawn git clone \
  --branch $env(WRL_BRANCH) \
  $env(WRL_REPO_URL)
expect eof

spawn git clone \
  $env(WRL_SBOM_URL)
expect eof

# run setup.sh to define your project configuration
spawn ./wrlinux-x/setup.sh \
  --distros $env(WRL_DISTRO) \
  --machines $env(WRL_MACHINE) \
  --dl-layers \
  --accept-eula yes
expect eof

exit
